### ISSUE TITLE
Invalid Token? after an hours?

### ISSUE THREAD

**Issue by ill02** [Zseni-Verified/AutoSend_Official#3]
![image](https://user-images.githubusercontent.com/81599806/143469205-ddcd1290-d021-4367-a847-ef3cfc78fd7b.png)

After an hours sending messages I got this error saying my token were invalid, tho i dont even touch the formats and settings in replit before it was still functioning or change my token either.

I also run few script using my token and it seems running well, also see if my account got locked but its all fine.
My Uptimerobot seems all fine too?.

**Comment by M2l2koPOWER** [comment]
but for me is a this is a constant problem, @Zseni051 What is the problem? How to fix it? Any ways to avoid it?
